# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/notification.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notification_window(object):
    def setupUi(self, notification_window):
        notification_window.setObjectName("notification_window")
        notification_window.resize(164, 164)
        notification_window.setMinimumSize(QtCore.QSize(164, 164))
        notification_window.setMaximumSize(QtCore.QSize(1231231, 1231231))
        font = QtGui.QFont()
        font.setPointSize(11)
        notification_window.setFont(font)
        notification_window.setWindowTitle("")
        notification_window.setWindowOpacity(1.0)
        self.main_layout = QtWidgets.QGridLayout(notification_window)
        self.main_layout.setObjectName("main_layout")
        self.notification = QtWidgets.QWidget(notification_window)
        self.notification.setObjectName("notification")
        self.gridLayout = QtWidgets.QGridLayout(self.notification)
        self.gridLayout.setObjectName("gridLayout")
        self.notification_icon = QtWidgets.QLabel(self.notification)
        self.notification_icon.setMaximumSize(QtCore.QSize(64, 64))
        self.notification_icon.setText("")
        self.notification_icon.setPixmap(QtGui.QPixmap(":/icons/icons/monev.png"))
        self.notification_icon.setScaledContents(True)
        self.notification_icon.setObjectName("notification_icon")
        self.gridLayout.addWidget(self.notification_icon, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.notification_message = QtWidgets.QLabel(self.notification)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notification_message.sizePolicy().hasHeightForWidth())
        self.notification_message.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.notification_message.setFont(font)
        self.notification_message.setText("")
        self.notification_message.setAlignment(QtCore.Qt.AlignCenter)
        self.notification_message.setWordWrap(True)
        self.notification_message.setObjectName("notification_message")
        self.gridLayout.addWidget(self.notification_message, 2, 0, 1, 3)
        self.main_layout.addWidget(self.notification, 2, 0, 1, 1)

        self.retranslateUi(notification_window)
        QtCore.QMetaObject.connectSlotsByName(notification_window)

    def retranslateUi(self, notification_window):
        pass
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    notification_window = QtWidgets.QWidget()
    ui = Ui_notification_window()
    ui.setupUi(notification_window)
    notification_window.show()
    sys.exit(app.exec_())
